package cn.local.jobassistant;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.net.Uri;
import android.os.*;
import android.provider.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import cn.local.jobassistant.core.*;
import org.json.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;

public final class MainActivity extends Activity {
    public static final String[] PROFILE_FIELDS={"姓名","年龄","学历专业","学校","毕业时间","技能","证书","项目","经历","当前所在地","目标城市","到岗时间","期望工资","加班安排","出差安排","大小周安排","夜班安排","求职状态","离职原因","联系方式","其他条件"};
    private AssistantApp app;
    private LinearLayout body,root;
    private TextView stateText,noticeText;
    private String screen="home",detailId="";
    private char[] backupPassword;
    private static final int IMPORT_RESUME=10,EXPORT_BACKUP=11,IMPORT_BACKUP=12;
    private final BroadcastReceiver changes=new BroadcastReceiver(){public void onReceive(Context c,Intent i){refreshHeader();}};
    @Override public void onCreate(Bundle b){super.onCreate(b);app=(AssistantApp)getApplication();getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);show(app.key.present()?"home":"key");}
    @Override protected void onStart(){super.onStart();IntentFilter f=new IntentFilter(getPackageName()+".CHANGED");if(Build.VERSION.SDK_INT>=33)registerReceiver(changes,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(changes,f);}
    @Override protected void onStop(){unregisterReceiver(changes);super.onStop();}
    @Override protected void onDestroy(){if(backupPassword!=null)Arrays.fill(backupPassword,'\0');super.onDestroy();}
    @Override public void onBackPressed(){if(!screen.equals("home"))show("home");else new AlertDialog.Builder(this).setTitle("退出求职助手？").setMessage("停止任务并清除内存中的 API Key。BOSS 官方 APP 登录状态需在 BOSS 内退出。").setNegativeButton("留在 APP",null).setPositiveButton("退出并清除 Key",(d,w)->{app.key.clear();stopAll();finishAndRemoveTask();}).show();}
    public void show(String page){
        screen=page;root=Ui.column(this);root.setBackgroundColor(Ui.BG);root.setPadding(Ui.dp(this,14),0,Ui.dp(this,14),0);
        root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(Ui.dp(this,14),insets.getSystemWindowInsetTop(),Ui.dp(this,14),insets.getSystemWindowInsetBottom());return insets;});
        TextView brand=Ui.text(this,"求职助手  /  BOSS",17,Ui.TEAL);brand.setTypeface(null,1);root.addView(brand);
        LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER_VERTICAL);stateText=Ui.text(this,app.status(),13,Ui.INK);bar.addView(stateText,new LinearLayout.LayoutParams(0,-2,1));Button stop=new Button(this);stop.setText("立即停止");stop.setTextColor(0xffb3261e);stop.setAllCaps(false);stop.setOnClickListener(v->stopAll());bar.addView(stop);root.addView(bar);
        noticeText=Ui.text(this,app.notice,13,Ui.MUTED);root.addView(noticeText);noticeText.setVisibility(app.notice.isBlank()?View.GONE:View.VISIBLE);
        ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);body=Ui.column(this);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout tabs=new LinearLayout(this);String[] ids={"home","jobs","chats","resumes","profile"},names={"首页","岗位","HR消息","简历","资料"};for(int i=0;i<ids.length;i++){String id=ids[i];Button t=new Button(this);t.setText(names[i]);t.setTextSize(12);t.setAllCaps(false);t.setPadding(0,0,0,0);t.setTextColor(id.equals(page)?Ui.TEAL:Ui.MUTED);t.setOnClickListener(v->show(id));tabs.addView(t,new LinearLayout.LayoutParams(0,Ui.dp(this,50),1));}root.addView(tabs);setContentView(root);
        if(app.vault==null){body.addView(Ui.title(this,"本地数据需要处理"));paragraph(body,app.storageFailure);button(body,"明确清除损坏数据并重新开始",()->confirm("清除全部数据？","此操作无法撤销。未确定的发送记录也会丢失，之后请人工核对 BOSS。",()->{Vault.erase(this);app.vault=new Vault(this);app.storageFailure="";show("key");}));return;}
        switch(page){case "key"->keyPage();case "home"->home();case "jobs"->jobs();case "job"->jobDetail();case "jobEdit"->jobEdit();case "chats"->chats();case "chat"->chatDetail();case "chatEdit"->chatEdit();case "resumes"->resumes();case "profile"->profile();case "faq"->faq();case "settings"->settings();case "bindings"->bindings();case "backup"->backup();case "privacy"->privacy();default->home();}
    }
    private void refreshHeader(){if(stateText!=null)stateText.setText(app.status());if(noticeText!=null){noticeText.setText(app.notice);noticeText.setVisibility(app.notice.isBlank()?View.GONE:View.VISIBLE);}}
    private void paragraph(LinearLayout p,String t){p.addView(Ui.text(this,t,14,Ui.MUTED));}
    private Button button(LinearLayout p,String label,Runnable r){return Ui.button(this,p,label,()->{try{r.run();}catch(Exception e){app.notice=AssistantApp.safeError(e);refreshHeader();}});}
    private LinearLayout card(String title){return Ui.card(this,body,title);}
    private void confirm(String title,String message,Runnable yes){new AlertDialog.Builder(this).setTitle(title).setMessage(message).setNegativeButton("取消",null).setPositiveButton("确认",(d,w)->{try{yes.run();}catch(Exception e){app.notice=AssistantApp.safeError(e);refreshHeader();}}).show();}
    private JSONObject data(){return app.vault.read();}
    private static String value(EditText e){return e.getText().toString().trim();}
    private static char[] chars(EditText e){char[] c=new char[e.length()];e.getText().getChars(0,e.length(),c,0);return c;}
    private void stopAll(){app.stop(RunGate.State.STOPPED,"任务已立即停止");stopService(new Intent(this,RunService.class));}
    private void keyPage(){
        body.addView(Ui.title(this,"连接你的 AI"));paragraph(body,"Key 仅在这次运行的内存中使用。完全重新打开 APP 时需要再次输入，后台超过 30 分钟会自动清除。");
        LinearLayout c=card("DeepSeek API Key");EditText key=Ui.field(this,c,"不会保存到手机或上传 GitHub","",false);key.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);key.setImportantForAutofill(View.IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS);
        CheckBox reveal=new CheckBox(this);reveal.setText("显示字符");reveal.setOnCheckedChangeListener((b,checked)->{key.setInputType(InputType.TYPE_CLASS_TEXT|(checked?InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD:InputType.TYPE_TEXT_VARIATION_PASSWORD));key.setSelection(key.length());});c.addView(reveal);
        paragraph(c,"服务地址："+J.object(data(),"ai").optString("baseUrl")+"\n连接测试会产生一次很小的 AI 调用。分析岗位或回复时，你确认的资料和相关聊天会发往此地址。");
        button(c,"测试连接并进入",()->{char[] secret=chars(key);key.setText("");try{app.key.set(secret);}finally{Arrays.fill(secret,'\0');}app.notice="正在测试连接…";refreshHeader();app.work(()->{try{app.ai.json("返回 JSON {\"ok\":true}",J.obj("test","connection"));}catch(Exception e){app.key.clear();throw e;}return null;},()->{app.notice="AI 连接成功";show("home");});});
        button(c,"先配置资料与求职条件",()->show("profile"));button(c,"调整 API 地址和模型",()->show("settings"));
    }
    private void home(){
        body.addView(Ui.title(this,"今天，专注合适的机会"));JSONObject s=data();String day=Ledger.day(System.currentTimeMillis());int scanned=0,matched=0,scored=0,applied=0,hr=0,replies=0,waiting=0,interviews=0;
        for(JSONObject j:J.list(J.array(s,"jobs")))if(day.equals(Ledger.day(j.optLong("time")))){scanned++;if(j.has("score"))scored++;if(j.optInt("score")>=J.object(s,"prefs").optInt("threshold",70))matched++;}
        JSONObject out=J.object(s,"outbox");for(Iterator<String> it=out.keys();it.hasNext();){JSONObject x=out.optJSONObject(it.next());if(x!=null&&"apply".equals(x.optString("kind"))&&"SENT".equals(x.optString("state"))&&day.equals(x.optString("day")))applied++;}
        for(JSONObject c:J.list(J.array(s,"chats"))){if(c.optBoolean("waiting")||c.optString("state").equals("等待本人处理"))waiting++;if(day.equals(Ledger.day(c.optLong("time")))){hr++;if(c.optString("category").equals("面试"))interviews++;}for(JSONObject a:J.list(J.array(c,"audit")))if(a.optBoolean("automatic")&&day.equals(Ledger.day(a.optLong("time"))))replies++;}
        LinearLayout stats=card("今日进度");String[] labels={"扫描岗位","符合条件","AI筛选","已投递","HR会话更新","自动回复","等待本人","面试邀请"};int[] counts={scanned,matched,scored,applied,hr,replies,waiting,interviews};for(int i=0;i<labels.length;i+=2){LinearLayout row=new LinearLayout(this);for(int n=i;n<i+2;n++){TextView t=Ui.text(this,counts[n]+"  "+labels[n],15,Ui.INK);row.addView(t,new LinearLayout.LayoutParams(0,-2,1));}stats.addView(row);}
        LinearLayout run=card("运行模式");RadioGroup modes=new RadioGroup(this);String[] names={"测试模式 · 只读取和分析","半自动 · 每次发送前确认","自动 · 按规则处理"};for(int i=0;i<3;i++){RadioButton b=new RadioButton(this);b.setId(100+i);b.setText(names[i]);modes.addView(b);}modes.check(100+app.gate.mode().ordinal());modes.setOnCheckedChangeListener((g,id)->{app.stop(RunGate.State.STOPPED,"模式已切换，请重新开始");app.gate.mode(RunGate.Mode.values()[id-100]);refreshHeader();});run.addView(modes);
        button(run,"开始 / 继续求职",()->{if(!app.key.present()){show("key");return;}if(BossService.current==null){permissions();return;}Runnable start=()->{if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},20);app.gate.start(true);startForegroundService(new Intent(this,RunService.class));BossService.current.begin();openBoss();};if(app.gate.mode()==RunGate.Mode.AUTO)confirm("启动自动模式？","将按已确认规则操作 BOSS 可见页面。未知、敏感问题会先回应并提醒你；遇到安全验证立即暂停。当前适配仍需真机验收，建议先用测试模式核对。",start);else start.run();});
        button(run,"暂停",()->app.stop(RunGate.State.PAUSED,"任务已暂停，可由本人继续"));button(run,app.key.present()?"更换 / 清除 API Key":"输入 API Key",()->{app.key.clear();app.stop(RunGate.State.KEY_REQUIRED,"请重新输入 API Key");show("key");});
        LinearLayout setup=card("准备与设置");paragraph(setup,"1. 导入并核对简历、资料\n2. 设置岗位条件和常见问题\n3. 手动登录 BOSS，完成控件适配\n4. 先用测试模式核对读取内容");button(setup,"求职条件、费用上限与权限",()->show("settings"));button(setup,"BOSS 页面适配",()->show("bindings"));
        JSONObject u=Ledger.usage(s,System.currentTimeMillis());paragraph(body,"今日 AI 调用 "+u.optInt("calls")+" 次 · 约 "+u.optLong("tokens")+" tokens\n费用估计 "+String.format(Locale.ROOT,"%.4f",u.optDouble("cost",0))+"（按设置单价；未设置时不代表免费）");
        paragraph(body,"v0.1.0 · 工程验证版\n真实 BOSS 投递、回复和简历附件发送尚需手机联调。首次沟通结果需本人核对；不会显示未经确认的成功记录。");
    }
    private void jobs(){
        body.addView(Ui.title(this,"岗位"));button(body,"录入岗位 / 粘贴 JD",()->{detailId="";show("jobEdit");});
        List<JSONObject> items=J.list(J.array(data(),"jobs"));Collections.reverse(items);if(items.isEmpty())paragraph(body,"尚未读取岗位。可在 BOSS 测试模式读取，或先录入一个真实岗位进行 AI 分析。");
        for(JSONObject j:items){LinearLayout c=card(j.optString("title"));paragraph(c,j.optString("company")+" · "+j.optString("city")+" · "+j.optString("salary")+"\n"+j.optString("status")+(j.has("score")?" · "+j.optInt("score")+"分":""));button(c,"查看岗位与分析",()->{detailId=j.optString("id");show("job");});}
    }
    private void jobEdit(){
        body.addView(Ui.title(this,"录入真实岗位"));JSONObject j=detailId.isEmpty()?J.obj():app.item("jobs",detailId);Map<String,EditText> fields=new LinkedHashMap<>();String[] keys={"title","company","city","salary","experience","education","hr","jd"},labels={"岗位名称","公司","城市","薪资","经验要求","学历要求","HR姓名","岗位 JD"};for(int i=0;i<keys.length;i++)fields.put(keys[i],Ui.field(this,body,labels[i],j.optString(keys[i]),keys[i].equals("jd")));
        button(body,"保存并分析",()->{JSONObject n=J.obj();fields.forEach((k,v)->J.put(n,k,value(v)));String id=Ids.job(n);if(id.isBlank())throw new IllegalArgumentException("请填写岗位、公司、城市和 HR");J.put(n,"id",id);J.put(n,"status","发现岗位");J.put(n,"time",System.currentTimeMillis());app.vault.update(s->{JSONArray a=J.array(s,"jobs");for(int i=0;i<a.length();i++)if(id.equals(a.optJSONObject(i).optString("id"))){a.remove(i);break;}a.put(n);J.put(s,"jobs",a);});detailId=id;if(app.key.present())app.engine.score(id);show("job");});
    }
    private void jobDetail(){
        JSONObject j=app.item("jobs",detailId);body.addView(Ui.title(this,j.optString("title")));paragraph(body,j.optString("company")+" · "+j.optString("city")+"\n"+j.optString("salary")+" / "+j.optString("education")+" / "+j.optString("experience")+"\nHR："+j.optString("hr")+"\n状态："+j.optString("status"));
        LinearLayout c=card("岗位描述");paragraph(c,j.optString("jd"));JSONObject a=J.object(j,"analysis");LinearLayout score=card(j.has("score")?"匹配评分 "+j.optInt("score")+" / 100":"等待分析");paragraph(score,"匹配原因："+a.optString("matches","尚无")+"\n不匹配："+a.optString("gaps","尚无")+"\n风险："+a.optString("risks","尚无")+"\n"+j.optString("reason"));paragraph(score,"招呼草稿："+j.optString("greeting"));button(score,"重新分析",()->{if(!app.key.present()){show("key");return;}app.engine.score(detailId);app.notice="正在分析，完成后点刷新";refreshHeader();});button(score,"刷新结果",()->show("job"));
        button(body,"在 BOSS 核对并投递",()->{if(app.gate.mode()==RunGate.Mode.TEST)throw new IllegalArgumentException("测试模式不会投递，请切换半自动模式");if(BossService.current==null)throw new IllegalArgumentException("请开启 BOSS 辅助权限");confirm("核对这个岗位并投递？","请在 60 秒内打开同一岗位。首次沟通可能发送 BOSS 官方默认招呼；生成的个性化草稿可由你核对后补发。",()->{app.gate.start(app.key.present());BossService.current.armJob(detailId);openBoss();});});
        if(!j.optString("task").isBlank())button(body,"我已在 BOSS 核实投递成功",()->confirm("确认投递结果","只在 BOSS 显示成功后确认。未确认的任务不会重试。",()->{app.vault.update(s->Ledger.sent(s,j.optString("task"),System.currentTimeMillis()));app.editItem("jobs",detailId,x->J.put(x,"status","已投递"));show("job");}));
        button(body,"加入公司黑名单",()->{app.vault.update(s->{JSONObject p=J.object(s,"prefs");J.put(p,"blackCompanies",p.optString("blackCompanies")+"\n"+j.optString("company"));});app.editItem("jobs",detailId,x->J.put(x,"status","黑名单岗位"));show("job");});
    }
    private void chats(){
        body.addView(Ui.title(this,"HR 消息"));button(body,"录入聊天与完整上下文",()->{detailId="";show("chatEdit");});List<JSONObject> items=J.list(J.array(data(),"chats"));Collections.reverse(items);if(items.isEmpty())paragraph(body,"尚无聊天记录。开启 BOSS 消息提醒后，新通知会提醒你打开对应会话。通知摘要不会直接触发发送。");
        for(JSONObject c:items){LinearLayout card=card(c.optString("hr")+" · "+c.optString("company"));paragraph(card,c.optString("title")+"\n"+c.optString("lastHr")+"\n"+c.optString("state"));button(card,"查看 / 回复 / 接管",()->{detailId=c.optString("id");show("chat");});}
    }
    private void chatEdit(){
        body.addView(Ui.title(this,"核对 HR 上下文"));JSONObject c=detailId.isBlank()?J.obj():app.item("chats",detailId);
        EditText hr=Ui.field(this,body,"HR姓名",c.optString("hr"),false),company=Ui.field(this,body,"公司",c.optString("company"),false),title=Ui.field(this,body,"岗位",c.optString("title"),false),jd=Ui.field(this,body,"完整岗位JD",J.object(c,"job").optString("jd"),true),history=Ui.field(this,body,"此前完整聊天（注明HR/本人）",c.optString("priorContext"),true),question=Ui.field(this,body,"本轮 HR 问题",c.optString("lastHr"),true);
        CheckBox reviewed=new CheckBox(this);reviewed.setText("我已核对双方身份、岗位和聊天上下文");body.addView(reviewed);
        button(body,"保存已确认的上下文",()->{if(!reviewed.isChecked()||value(hr).isBlank()||value(company).isBlank()||value(title).isBlank()||value(question).isBlank())throw new IllegalArgumentException("请补齐身份、问题并勾选核对");String id=detailId.isBlank()?Ids.hash(value(hr),value(company),value(title)):detailId;JSONObject n=app.item("chats",id);if(n.length()==0)n=J.obj("id",id,"history",new JSONArray(),"audit",new JSONArray());J.put(n,"hr",value(hr));J.put(n,"company",value(company));J.put(n,"title",value(title));J.put(n,"lastHr",value(question));if(!value(question).equals(c.optString("lastHr"))||n.optString("messageId").isBlank())J.put(n,"messageId",Ids.hash("manual",value(question),value(history)));J.put(n,"priorContext",value(history));J.put(n,"job",J.obj("title",value(title),"company",value(company),"jd",value(jd)));J.put(n,"contextConfirmed",true);J.put(n,"time",System.currentTimeMillis());J.put(n,"state","等待本人处理");JSONObject finalN=n;app.vault.update(s->{JSONArray a=J.array(s,"chats");for(int i=0;i<a.length();i++)if(id.equals(a.optJSONObject(i).optString("id"))){a.remove(i);break;}a.put(finalN);J.put(s,"chats",a);});detailId=id;show("chat");});
    }
    private void chatDetail(){
        JSONObject c=app.item("chats",detailId);body.addView(Ui.title(this,c.optString("hr")+" · "+c.optString("company")));paragraph(body,c.optString("title")+"\n状态："+c.optString("state")+"\nHR："+c.optString("lastHr"));
        button(body,"核对 / 补全岗位和聊天上下文",()->show("chatEdit"));
        button(body,c.optBoolean("takeover")?"恢复 AI（仍需开始任务）":"人工接管此会话",()->{app.editItem("chats",detailId,j->{J.put(j,"takeover",!c.optBoolean("takeover"));J.put(j,"state",!c.optBoolean("takeover")?"人工处理中":"等待本人处理");});show("chat");});
        LinearLayout d=card("回复草稿");EditText reply=Ui.field(this,d,"请核对后发送",c.optString("draft"),true);CheckBox learn=new CheckBox(this);learn.setText("发送确认后，将我的答案保存为同类问题的默认答案");d.addView(learn);
        button(d,"生成 AI 回复",()->{if(!app.key.present()){show("key");return;}app.engine.reply(detailId);app.notice="正在生成；完成后点刷新。等待本人回答时不会反复拖延。";refreshHeader();});button(d,"刷新草稿",()->show("chat"));
        button(d,"保存我的补充回复",()->{String text=value(reply);if(text.isBlank()||text.length()>350)throw new IllegalArgumentException("回复请输入 1–350 字");if(Privacy.sensitive(text)||Privacy.hasSecret(text))throw new IllegalArgumentException("敏感资料请到 BOSS 官方 APP 人工处理");app.editItem("chats",detailId,j->{J.put(j,"draft",text);J.put(j,"edited",true);J.put(j,"holding",false);J.put(j,"draftMessageId",j.optString("messageId"));J.put(j,"saveAnswerRequested",learn.isChecked());J.put(j,"category",ReplyPolicy.classify(j.optString("lastHr")));});show("chat");});
        button(d,"在 BOSS 核对并发送",()->{if(app.gate.mode()==RunGate.Mode.TEST)throw new IllegalArgumentException("测试模式不会发送，请先切换半自动模式");if(BossService.current==null)throw new IllegalArgumentException("请开启 BOSS 辅助权限");if(!value(reply).equals(c.optString("draft")))throw new IllegalArgumentException("请先保存修改后的回复");confirm("发送给这个 HR？","请在 60 秒内打开相同会话。页面身份、新消息和输入框会再次核对；人工接管期间不会代发。",()->{app.gate.start(app.key.present());BossService.current.armChat(detailId);openBoss();});});
        button(d,"我已在 BOSS 手动发送，登记结果",()->confirm("确认已手动发送？","只记录你已发送的内容，不会再次点击 BOSS。",()->{String text=value(reply);if(text.isBlank())throw new IllegalArgumentException("请填写实际发送内容");String task=Ids.hash("manual",detailId,c.optString("messageId"),text);final boolean[] ok={false};app.vault.update(s->ok[0]=Ledger.reserve(s,task,"message",detailId,System.currentTimeMillis(),0,30));if(!ok[0])throw new IllegalArgumentException("此结果已登记");app.editItem("chats",detailId,j->{J.put(j,"edited",true);J.put(j,"holding",false);J.put(j,"saveAnswerRequested",learn.isChecked());});app.engine.recordSent(detailId,task,text,false);show("chat");}));
        LinearLayout audit=card("本地回复记录");for(JSONObject a:J.list(J.array(c,"audit")))paragraph(audit,time(a.optLong("time"))+" · "+(a.optBoolean("automatic")?"自动":"本人确认")+"\nHR："+a.optString("question")+"\n发送："+a.optString("sent"));
    }
    private void resumes(){
        body.addView(Ui.title(this,"我的简历"));paragraph(body,"支持 PDF、DOCX、TXT，最大 5 MB / 30 页。提取后必须由你核对，才会用于 AI 判断。扫描图片暂不支持识别。");button(body,"导入简历",()->startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document","text/plain"}),IMPORT_RESUME));
        for(JSONObject r:J.list(J.array(data(),"resumes"))){LinearLayout c=card(r.optString("name")+(r.optBoolean("default")?" · 默认":""));paragraph(c,r.optBoolean("approved")?"已由本人核对":"等待本人核对");EditText text=Ui.field(this,c,"核对学历、技能、经历与联系方式",r.optString("text"),true);button(c,"我已核对，保存文字",()->{app.editItem("resumes",r.optString("id"),j->{J.put(j,"text",value(text));J.put(j,"approved",true);});show("resumes");});button(c,"设为默认简历",()->{app.vault.update(s->{for(JSONObject x:J.list(J.array(s,"resumes")))J.put(x,"default",x.optString("id").equals(r.optString("id")));});show("resumes");});button(c,"删除此版本",()->confirm("删除此简历？","只删除助手本地副本。",()->{remove("resumes",r.optString("id"));show("resumes");}));}
        paragraph(body,"此版会用已确认简历进行分析；向 HR 发送附件需在 BOSS 官方 APP 选择对应简历。自动附件发送尚未通过真机验收。");
    }
    private void profile(){body.addView(Ui.title(this,"我的真实资料"));paragraph(body,"留空就是未知。请填写可直接告诉 HR 的真实情况；不要填写密码、验证码或证件号码。");JSONObject p=J.object(data(),"profile");Map<String,EditText> fields=new LinkedHashMap<>();for(String k:PROFILE_FIELDS)fields.put(k,Ui.field(this,body,k,p.optString(k),Set.of("技能","项目","经历","其他条件").contains(k)));button(body,"保存资料",()->{JSONObject v=J.obj();fields.forEach((k,e)->J.put(v,k,value(e)));if(v.toString().matches("(?is).*sk-[a-z0-9_-]{8,}.*"))throw new IllegalArgumentException("请勿将 API Key 填入个人资料");app.vault.update(s->J.put(s,"profile",v));app.notice="真实资料已保存";show("profile");});button(body,"我的 HR 常见问题",()->show("faq"));button(body,"设置、备份与隐私",()->show("settings"));}
    private void faq(){
        body.addView(Ui.title(this,"我的 HR 常见问题"));paragraph(body,"每条答案需你确认，AI 只会使用已授权的真实答案。敏感信息不会自动发送。");
        for(JSONObject f:J.list(J.array(data(),"faq"))){LinearLayout c=card(f.optString("category"));paragraph(c,f.optString("question"));EditText a=Ui.field(this,c,"默认答案",f.optString("answer"),true);button(c,"保存修改",()->{app.editItem("faq",f.optString("id"),x->J.put(x,"answer",value(a)));show("faq");});button(c,"删除答案",()->{remove("faq",f.optString("id"));show("faq");});}
        LinearLayout n=card("添加已确认的答案");Spinner category=new Spinner(this);category.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,ReplyPolicy.CATEGORIES));n.addView(category);EditText q=Ui.field(this,n,"问题","",false),a=Ui.field(this,n,"我授权使用的真实答案","",true);button(n,"添加并授权",()->{if(value(a).isBlank()||Privacy.hasSecret(value(a))||Privacy.sensitive(value(a)))throw new IllegalArgumentException("答案为空或包含敏感信息");app.vault.update(s->J.array(s,"faq").put(J.obj("id",UUID.randomUUID().toString(),"category",category.getSelectedItem().toString(),"question",value(q),"answer",value(a),"approved",true)));show("faq");});
    }
    private void settings(){
        body.addView(Ui.title(this,"求职与安全设置"));JSONObject s=data(),p=J.object(s,"prefs"),ai=J.object(s,"ai");LinearLayout c=card("岗位条件");Map<String,EditText> pf=new LinkedHashMap<>();String[][] strings={{"job","目标岗位"},{"city","目标城市"},{"education","学历要求（空为不限）"},{"experience","经验要求（空为不限）"},{"type","实习 / 全职（空为不限）"},{"keywords","岗位关键词，逗号分隔"},{"companyKeywords","公司关键词"},{"blackCompanies","黑名单公司"},{"blackJobs","黑名单岗位"}};for(String[] f:strings)pf.put(f[0],Ui.field(this,c,f[1],p.optString(f[0]),false));String[][] numbers={{"minSalary","最低月薪（元）"},{"maxSalary","最高月薪（元）"},{"threshold","候选评分门槛（0–100）"},{"dailyApplications","每日最大投递（1–100）"},{"dailyCalls","每日 AI 调用（1–500）"},{"dailyTokens","每日 token 上限"},{"dailyCost","每日费用上限（0为关闭）"},{"intervalSeconds","操作最短间隔秒数（至少5）"},{"dedupDays","同岗位去重天数"}};for(String[] f:numbers)pf.put(f[0],Ui.field(this,c,f[1],p.optString(f[0]),false));CheckBox official=new CheckBox(this);official.setText("允许点击“立即沟通”（可能发送 BOSS 默认招呼）");official.setChecked(p.optBoolean("allowBossGreeting"));c.addView(official);
        button(c,"保存求职条件和限额",()->{JSONObject v=J.obj();for(String[] f:strings)J.put(v,f[0],value(pf.get(f[0])));for(String[] f:numbers){double n=Double.parseDouble(value(pf.get(f[0])));if(!Double.isFinite(n))throw new IllegalArgumentException("请输入有效数字");J.put(v,f[0],n);}if(v.optInt("dailyApplications")<1||v.optInt("dailyApplications")>100||v.optInt("dailyCalls")<1||v.optInt("dailyCalls")>500||v.optInt("threshold")<0||v.optInt("threshold")>100||v.optInt("intervalSeconds")<5||v.optInt("dailyTokens")<1000||v.optInt("dedupDays")<1||v.optInt("dedupDays")>3650||v.optDouble("dailyCost")<0||v.optInt("minSalary")<0||v.optInt("maxSalary")<v.optInt("minSalary"))throw new IllegalArgumentException("请检查限额、间隔和薪资范围");J.put(v,"allowBossGreeting",official.isChecked());app.stop(RunGate.State.STOPPED,"求职条件已更新，请重新开始");app.vault.update(x->J.put(x,"prefs",v));show("settings");});
        LinearLayout api=card("AI 服务");EditText base=Ui.field(this,api,"Base URL",ai.optString("baseUrl"),false),model=Ui.field(this,api,"Model Name",ai.optString("model"),false),temp=Ui.field(this,api,"Temperature 0–2",ai.optString("temperature"),false),priceIn=Ui.field(this,api,"每百万输入 tokens 单价（自行核对官方价格）",ai.optString("inputPrice"),false),priceOut=Ui.field(this,api,"每百万输出 tokens 单价",ai.optString("outputPrice"),false);
        button(api,"保存 AI 配置",()->{Privacy.endpoint(value(base));double t=Double.parseDouble(value(temp)),in=Double.parseDouble(value(priceIn)),out=Double.parseDouble(value(priceOut));if(!Double.isFinite(t)||!Double.isFinite(in)||!Double.isFinite(out)||t<0||t>2||in<0||out<0||value(model).isBlank())throw new IllegalArgumentException("请检查模型、温度或单价");confirm("确认 AI 服务地址","Key 和分析所需资料将直接发送至："+value(base)+"。请确认这是你信任的服务商。保存后需重新输入 Key。",()->{app.key.clear();app.stop(RunGate.State.KEY_REQUIRED,"API 配置已更新");app.vault.update(x->J.put(x,"ai",J.obj("baseUrl",value(base),"model",value(model),"temperature",t,"inputPrice",in,"outputPrice",out)));show("key");});});
        button(body,"权限与后台运行说明",this::permissions);button(body,"打开 BOSS 官方 APP 登录",this::openBoss);button(body,"绑定 BOSS 控件",()->show("bindings"));button(body,"加密备份与隐私清除",()->show("backup"));button(body,"隐私说明 / 版本",()->show("privacy"));
    }
    private void permissions(){new AlertDialog.Builder(this).setTitle("仅申请求职所需权限").setMessage("无障碍：读取 BOSS 可见岗位和聊天，按授权输入与点击。\n通知读取（可选）：只提醒 BOSS 新消息，其他 APP 内容立即丢弃。\n后台运行：使用有暂停/停止按钮的前台通知。锁屏或 BOSS 页面不可见时停止点击，不绕过系统限制。\n电池优化可能结束任务，可在系统的应用电池设置中手动调整。").setPositiveButton("无障碍设置",(d,w)->startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))).setNeutralButton("通知读取设置",(d,w)->startActivity(new Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS))).setNegativeButton("关闭",null).show();}
    private void openBoss(){Intent intent=getPackageManager().getLaunchIntentForPackage(BossService.PACKAGE);if(intent==null){new AlertDialog.Builder(this).setTitle("请先安装 BOSS 直聘官方 APP").setMessage("在手机应用商店安装官方 BOSS 直聘，然后手动登录。助手不会索取 BOSS 密码。").setPositiveButton("知道了",null).show();return;}startActivity(intent);}
    private void bindings(){
        body.addView(Ui.title(this,"BOSS 页面适配"));paragraph(body,"BOSS 控件随版本变化。此工程版需要在手机上完成绑定和测试模式验收。只使用可见控件 ID；未匹配时暂停。请勿将双方消息气泡绑定为同一控件。");button(body,"读取当前 BOSS 页面的控件列表",()->{if(BossService.current==null){permissions();return;}app.stop(RunGate.State.STOPPED,"正在等待读取 BOSS 页面");BossService.captureRequested=true;openBoss();});button(body,"刷新控件列表",()->show("bindings"));JSONObject b=J.object(data(),"bindings");for(int i=0;i<BossService.ROLES.length;i++){String role=BossService.ROLES[i],label=BossService.LABELS[i];LinearLayout c=card(label);paragraph(c,b.optString(role,"尚未绑定"));button(c,"选择控件",()->{if(BossService.inventory.isEmpty())throw new IllegalArgumentException("请先读取 BOSS 当前页面");String[] choices=BossService.inventory.toArray(new String[0]);new AlertDialog.Builder(this).setTitle(label).setItems(choices,(d,index)->{app.vault.update(s->J.put(J.object(s,"bindings"),role,choices[index]));show("bindings");}).setNegativeButton("取消",null).show();});}button(body,"清除控件绑定",()->confirm("清除绑定？","不会删除资料、聊天或去重记录。",()->{app.stop(RunGate.State.STOPPED,"绑定已清除");app.vault.update(s->J.put(s,"bindings",J.obj()));show("bindings");}));
    }
    private void backup(){
        body.addView(Ui.title(this,"备份与隐私清除"));paragraph(body,"加密备份只含个人资料、求职设置与已授权 FAQ。没有 API Key、BOSS 登录信息、聊天和简历附件。请记住密码；丢失无法恢复。");EditText password=Ui.field(this,body,"备份密码（至少10个字符）","",false);password.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);
        button(body,"导出加密备份",()->{setBackupPassword(password);startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/octet-stream").addCategory(Intent.CATEGORY_OPENABLE).putExtra(Intent.EXTRA_TITLE,"job-assistant-backup.jab"),EXPORT_BACKUP);});
        button(body,"导入备份",()->{setBackupPassword(password);confirm("导入备份？","将替换个人资料、求职设置和 FAQ；保留本机发送去重记录。",()->startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),IMPORT_BACKUP));});
        button(body,"清除 HR 聊天记录",()->confirm("清除聊天？","发送任务指纹会保留，避免重复发送。",()->{app.stop(RunGate.State.STOPPED,"聊天已清除");app.vault.update(s->J.put(s,"chats",new JSONArray()));show("backup");}));button(body,"清除岗位记录",()->confirm("清除岗位？","发送任务指纹会保留，避免重复投递。",()->{app.stop(RunGate.State.STOPPED,"岗位已清除");app.vault.update(s->J.put(s,"jobs",new JSONArray()));show("backup");}));
        button(body,"退出 BOSS 登录状态",()->new AlertDialog.Builder(this).setTitle("在 BOSS 官方 APP 中退出").setMessage("助手没有保存 BOSS Cookie、Session 或密码，也无权删除另一 APP 的登录资料。请打开 BOSS → 我的 → 设置 → 账号相关页面，手动退出登录。临时登录应由你在使用结束时退出。").setPositiveButton("打开 BOSS",(d,w)->{stopAll();openBoss();}).setNegativeButton("取消",null).show());
        button(body,"清除全部本地数据",()->confirm("永久清除全部数据？","资料、简历、聊天、FAQ、备份密码和发送指纹将被删除。之后请手动核对历史投递，避免重复。导出的备份需在你选择的位置自行删除。",()->{stopAll();app.key.clear();Vault.erase(this);app.vault=new Vault(this);show("key");}));
    }
    private void setBackupPassword(EditText e){if(backupPassword!=null)Arrays.fill(backupPassword,'\0');backupPassword=chars(e);e.setText("");if(backupPassword.length<10){Arrays.fill(backupPassword,'\0');backupPassword=null;throw new IllegalArgumentException("备份密码至少10个字符");}}
    private void privacy(){body.addView(Ui.title(this,"隐私与使用边界"));paragraph(body,"求职助手 v0.1.0\n\nAPI Key 仅保存在当前进程内存；输入框不保存界面状态、不参与自动填充。退出或进程死亡后消失，后台30分钟后清除。网络库短暂创建的字符串由系统回收，不能承诺 RAM 物理取证清零。\n\n资料、简历、岗位、聊天与发送记录使用 Android Keystore + AES-GCM 加密在本机私有目录保存，禁用系统自动备份。没有开发者服务器、统计 SDK 或 HTTP 请求日志。只有你配置的 AI 服务接收分析需要的资料。\n\n助手只读取 BOSS 可见页面与 BOSS 通知。官方登录状态由 BOSS 管理。验证码、风控提示、登录失效和不可识别页面均停止，不破解、不伪装设备、不调用 BOSS 私有接口。\n\n此工程版需要真实手机适配与验收。后台服务保持任务状态和提醒；锁屏和不可见页面不能继续点击。自动附件发送、完整不可见历史采集以及首次投递确认仍未完成，不能把本版视作最终全自动成品。");button(body,"打开项目源码",()->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://github.com/yichuan-dev/ai-coding-lab/tree/boss-android/boss-assistant"))));}
    private void remove(String list,String id){app.vault.update(s->{JSONArray a=J.array(s,list);for(int i=0;i<a.length();i++)if(id.equals(a.optJSONObject(i).optString("id"))){a.remove(i);break;}});}
    private String time(long t){return new SimpleDateFormat("MM-dd HH:mm",Locale.CHINA).format(new Date(t));}
    @Override protected void onActivityResult(int request,int result,Intent intent){
        super.onActivityResult(request,result,intent);if(result!=RESULT_OK||intent==null||intent.getData()==null){if(backupPassword!=null){Arrays.fill(backupPassword,'\0');backupPassword=null;}return;}Uri uri=intent.getData();
        if(request==IMPORT_RESUME){String name="resume";try(Cursor cursor=getContentResolver().query(uri,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(cursor!=null&&cursor.moveToFirst())name=cursor.getString(0);}String filename=name;app.notice="正在读取简历…";refreshHeader();app.work(()->{byte[] bytes;try(InputStream in=getContentResolver().openInputStream(uri)){bytes=ResumeReader.bounded(in,5*1024*1024);}try{String text=ResumeReader.parse(this,filename,bytes);String encoded=android.util.Base64.encodeToString(bytes,android.util.Base64.NO_WRAP);app.vault.update(s->J.array(s,"resumes").put(J.obj("id",UUID.randomUUID().toString(),"name",filename,"text",text,"file",encoded,"approved",false,"default",J.array(s,"resumes").length()==0)));}finally{Arrays.fill(bytes,(byte)0);}return null;},()->{app.notice="简历已提取，请核对后确认";show("resumes");});}
        if(request==EXPORT_BACKUP||request==IMPORT_BACKUP){char[] pw=backupPassword;backupPassword=null;app.work(()->{try{if(pw==null)throw new IllegalArgumentException("请重新输入备份密码");if(request==EXPORT_BACKUP){byte[] bytes=app.vault.backup(pw);try(OutputStream out=getContentResolver().openOutputStream(uri)){out.write(bytes);}}else{app.stop(RunGate.State.STOPPED,"正在导入备份");byte[] bytes;try(InputStream in=getContentResolver().openInputStream(uri)){bytes=ResumeReader.bounded(in,10*1024*1024);}app.vault.restore(bytes,pw);}}finally{if(pw!=null)Arrays.fill(pw,'\0');}return null;},()->{app.notice="备份操作完成";show("backup");});}
    }
}
